name: swift_log
description: Streamline Your Logging Experience and Seamlessly Integrate with
  Any Backend System
version: 0.0.1
repository: https://github.com/knowbee/swift_log

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^8.1.0
  dio: ^5.1.1
  flutter:
    sdk: flutter
  logger: ^1.4.0
  path_provider: null

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
